config/routes.rb
Rails.application.routes.draw do
  root "contacts#index"

  devise_for :users

  namespace :api do
    namespace :v1 do

      resources :contacts, only: [:index, :show] do
        resources :notes, only: [:index, :create, :edit, :update]
      end

      resources :users, only: [:index, :show] do
        resources :contacts, only: [:index]
      end

      resources :notes, only: [:index, :show, :create, :edit]
    end
  end
  
  resources :contacts, only: [:index, :show, :create, :new, :edit, :update, :destroy]
  resources :users, only: [:index, :destroy]
  resources :notes, only: [:destroy, :edit, :update]

  get "*path", to: 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :notes
  belongs_to :user

  before_save :set_full_name

private

  def set_full_name
    self.full_name = "#{self.last_name}, #{self.first_name} ".strip
  end
end

app/models/note.rb
class Note < ApplicationRecord
validates :comment, presence: true

  belongs_to :contact
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  mount_uploader :avatar, AvatarUploader

  has_many :contacts
  has_many :notes

  def admin?
    admin == true
  end

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.avatar = auth.info.avatar # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails,
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
end


  before_save :set_full_name

private

  def set_full_name
    self.full_name = "#{self.last_name}, #{self.first_name} ".strip
  end
end

app/controllers/api/v1/contacts_controller.rb
class Api::V1::ContactsController < ApiController
  serialization_scope :current_user

  def index
    render json: Contact.where( :user => current_user).order('last_name')
  end

  def show
    render json: Contact.find(params[:id]), serializer: ContactShowSerializer
  end
end

app/controllers/api/v1/notes_controller.rb
class Api::V1::NotesController < ApplicationController

  def index
    if params[:contact_id]
      contact = Contact.find(params[:contact_id])
      notes = contact.notes
    else
      contacts = Contact.all
      notes = contacts
    end
    render json: notes
  end

  def show
    render json: Note.find(params[:id])
  end


  def create
    note = Note.new(note_params)

    note.contact = Contact.find(params[:contact_id])
    note.user = current_user
    note.save

    render json: note
  end

  private
  def note_params
    params.require(:note).permit(:comment)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  serialization_scope :current_user

  def index
    if user_signed_in? &&
      !current_user.nil? &&
      current_user.role == 'member' || current_user.role == 'admin'

      user = User.find(current_user.id)
      contacts = user.contacts
      render json: contacts

      else
      redirect_to contacts_path
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :store_action

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit({ role: ['member','admin'] }, :email, :first_name, :last_name, :full_name, :github_link, :linkedin_link, :password, :password_confirmation, :avatar)
    end
  end

  def store_action
    return unless request.get?
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      store_location_for(:user, "/contacts")
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :authorize_user, except: [:index]

  def index
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user

    if @contact.save
      flash[:success] = 'Contact added successfully'
      @contact.save
      redirect_to @contact
    else
      @errors = @contact.errors.full_messages
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      flash[:success] = 'Contact updated successfully'
      @contact = @contact.update(contact_params)
      redirect_to contact_path
    else
      @errors = @contact.errors.full_messages
      render :edit
    end

  end

  def destroy
    contact = Contact.find(params[:id])
    notes = contact.notes
    contact.destroy
    notes.destroy_all
    redirect_to users_path
  end

  protected
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :full_name, :email, :company, :past_company, :industry, :phone_number, :how_met, :last_contacted, :follow_up, :location, :family_details, :birthday)
  end

  def authorize_user
    if !user_signed_in?
      flash[:notice] = "You do not have access to this page."
      redirect_to root_path
    end
  end

  def authorize_admin
    if !user_signed_in? || !current_user.admin?
      flash[:notice] = "You do not have access to this page."
      redirect_to root_path
    end
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

before_action :authorize_user

  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to users_path
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(note_params)
      flash[:success] = 'Contact updated successfully'
      @note = @note.update(note_params)
      redirect_to contacts_path
    else
      @errors = @note.errors.full_messages
      render :edit
    end
  end

  protected

  def note_params
    params.require(:note).permit(:comment)
  end

  def authorize_user
    if !user_signed_in?
      flash[:notice] = "You do not have access to this page."
      redirect_to root_path
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin

  def index
    @users = User.all { |e|  }
    @contacts = Contact.all.order(:id)
    @notes = Note.all.order(:id)
  end

  def destroy
    user = User.find(params[:id])

    if user != current_user
      if user.contacts
        contacts = user.contacts
        current_user.contacts = contacts
      end
      user.notes.destroy_all
      user.contacts.destroy_all
      user.destroy
    else
      flash[:notice] = "Admins can't delete own account"
    end

    redirect_to users_path
  end

  def authorize_admin
    if !user_signed_in? || !current_user.admin?
      flash[:notice] = "You do not have access to this page."
      redirect_to root_path
    end
  end

end

app/views/contacts/DEPOT.erb
<div class="row">
  <div class="columns medium-8 medium-centered">

  <h1 class="page-header">Edit This Contact</h1>

  <% if @errors %>
    <div class="panel callout alert">
      <ul>
        <% @errors.each do |error|%>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <%end%>

  <%= form_for(@contact, :html => { :class => 'form' }) do |f| %>
  <div class="field">
    <%= f.label :first_name, class: "label" %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name, class: "label" %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :phone_number, class: "label" %><br />
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :email, :class => "label" %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :location, :class => "label" %><br />
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :company, :class => "label" %><br />
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :past_company, :class => "label" %><br />
    <%= f.text_field :past_company %>
  </div>

  <div class="field">
    <%= f.label :industry, class: "label" %><br />
    <%= f.text_field :industry %>
  </div>

  <div class="field">
    <%= f.label :how_met, :class => "label" %><br />
    <%= f.text_field :how_met %>
  </div>

  <div class="field">
    <%= f.label :last_contacted, :class => "label" %><br />
    <%= f.text_field :last_contacted %>
  </div>

  <div class="field">
    <%= f.label :follow_up, :class => "label" %><br />
    <%= f.text_field :follow_up %>
  </div>

  <div class="field">
    <%= f.label :birthday, :class => "label" %><br />
    <%= f.text_field :birthday %>
  </div>

  <div class="field">
    <%= f.label :family_details, :class => "label" %><br />
    <%= f.text_field :family_details %>
  </div>

    <div class="actions">
      <%= f.submit "Update", class: "button form-submit" %>
    </div>
  <% end %>

  </div>
</div>

app/views/contacts/edit.html.erb
<div id="app"></div>

app/views/contacts/index.html.erb
<div id="app"></div>

app/views/contacts/new.html.erb
<div class="row">
  <div class="columns medium-8 medium-centered">

    <h1 class="page-header">Add New Contact</h1>

    <% if @errors %>
      <div class="panel callout alert">
        <ul>
          <% @errors.each do |error|%>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <%end%>

    <%= form_for(@contact, :html => { :class => 'form', :id => "new_contact_form" }) do |f|  %>
    <div class="field">
      <%= f.label :first_name, class: "label" %><br />
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :last_name, class: "label" %><br />
      <%= f.text_field :last_name %>
    </div>

    <div class="field">
      <%= f.label :phone_number, class: "label" %><br />
      <%= f.text_field :phone_number %>
    </div>

    <div class="field">
      <%= f.label :email, :class => "label" %><br />
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :location, :class => "label" %><br />
      <%= f.text_field :location %>
    </div>

    <div class="field">
      <%= f.label :company, :class => "label" %><br />
      <%= f.text_field :company %>
    </div>

    <div class="field">
      <%= f.label :past_company, :class => "label" %><br />
      <%= f.text_field :past_company %>
    </div>

    <div class="field">
      <%= f.label :industry, class: "label" %><br />
      <%= f.text_field :industry %>
    </div>

    <div class="field">
      <%= f.label :how_met, :class => "label" %><br />
      <%= f.text_field :how_met %>
    </div>

    <div class="field">
      <%= f.label :last_contacted, :class => "label" %><br />
      <%= f.text_field :last_contacted, wrapper: {class: 'datepicker'} %>
    </div>

    <div class="field">
      <%= f.label :follow_up, :class => "label" %><br />
      <%= f.text_field :follow_up %>
    </div>

    <div class="field">
      <%= f.label :birthday, :class => "label" %><br />
      <%= f.text_field :birthday %>
    </div>

    <div class="field">
      <%= f.label :family_details, :class => "label" %><br />
      <%= f.text_field :family_details %>
    </div>

      <div class="actions">
        <%= f.submit "Add Contact", class: "button form-submit" %>
      </div>
    <% end %>

  </div>
<div>

app/views/contacts/show.html.erb
<div id="app"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>quikSave</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_pack_tag 'application'%>

  <%= csrf_meta_tags %>

  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-118991490-1"></script>

<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-118991490-1');
</script>

</head>
<body>

  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <a href="/contacts" class="header-logo"><span class="quikSave">quikSave</span></a>
      </li>

      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">

      <ul class="right">

        <% if user_signed_in? %>
          <li><a href="/quiz">Quiz Me!</a></li>  
          <li><%= link_to '+ Add New Contact', new_contact_path %></li>

          <% if current_user.admin? %>
            <li><%= link_to 'Manage Site', users_path %></li>
          <% end %>

          <li>
            <% if current_user.avatar.path.nil? %>
              <%= link_to 'Profile', edit_user_registration_path %>
            <% else %>
              <%= link_to edit_user_registration_path do %>
                <img src="<%= current_user.avatar %>" class="profile-avatar top-bar image--rounded">
                <% end %>
            <% end %>
          </li>

          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => "sign-out" %></li>

        <% else %>
          <li class="active"><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Log in', new_user_session_path %></li>

        <% end %>

        </ul>

      </section>
  </nav>

  <% if !flash.empty? %>
    <div class="row">
      <div class="columns medium-8 medium-centered">
        <div class="flash panel callout text-center">

          <%- flash.each do |key, value| -%>
            <div class="flash flash-<%= key %>">
              <%= value %>
            </div>
            <script>
              setTimeout("$('.flash').fadeOut('slow')", 1500)
            </script>
          <%- end -%>
          </div>
        </div>
      </div>
    <% end %>
    </li>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield :extra_footer %>
    <footer class="footer">
      <a href="">Contact</a>  Privacy Policy
    </footer>
  </body>
</html>

app/views/notes/edit.html.erb
<div class="row">
  <div class="columns medium-8 medium-centered">

  <h1 class="page-header">Edit This Note</h1>

  <% if @errors %>
    <div class="panel callout alert">
      <ul>
        <% @errors.each do |error|%>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <%end%>

  <%= form_for(@note, :html => { :class => 'form' }) do |f| %>
  <div class="field">
    <%= f.label :comment, class: "label" %><br />
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit "Update", class: "button form-submit" %>
  </div>
  <% end %>

  </div>
</div>

app/views/users/index.html.erb
<div class="row user-page">
  <div class="columns medium-11">

    <h1>Manage Users and Contacts</h1>

    <ul class="tabs admin-tabs" data-tab>
      <li class="tab-title active"><a href="#users">Users</a></li>
      <li class="tab-title"><a href="#contacts">Contacts</a></li>
    </ul>

    <div class="tabs-content admin-tabs-content">

      <div class="content active" id="users">
        <h2 class="content-type-header">Users</h2>

          <div class="row">
            <div class="columns small-4">
              <h4>Email</h4>
            </div>

            <div class="columns small-4">
              <h4>Last Logged In</h4>
            </div>

            <div class="columns small-4 text-center">
              <h4>Delete User</h4>
            </div>
          </div>

          <% @users.each do |user| %>
            <div class="row">
              <div class="columns small-4">
                <%= user.email %>
              </div>
              <div class="columns small-4">
                <%= user.last_sign_in_at %>
              </div>
              <div class="columns small-4 text-center">
                <%= link_to 'Delete', user, method: :delete, class: "button tiny alert user-#{user.id}" %>
              </div>
            </div>
          <% end %>
    </div>

    <div class="content" id="contacts">

      <h2 class="content-type-header">Contacts</h2>

      <div class="row">
        <div class="columns small-1 text-center">
            <h4>ID</h4>
          </div>

          <div class="columns small-4">
            <h4>Name</h4>
          </div>

          <div class="columns small-4 text-center">
            <h4>Delete Contact</h4>
          </div>
        </div>

        <% @contacts.each do |contact| %>
          <div class="row">
            <div class="columns small-1 text-center">
              <%= contact.id %>
            </div>
            <div class="columns small-4">
              <%= link_to "#{contact.full_name}", contact %>
            </div>
            <div class="columns small-4 text-center">
              <%= link_to 'Delete', contact, method: :delete, class: "button tiny alert contact-#{contact.id}" %>
            </div>
          </div>
        <% end %>

   </div>
  </div>
  </div>
</div>